import type { Metadata } from "next";
import { Poppins } from "next/font/google";  // Import Poppins font
import "./globals.css";
import 'aos/dist/aos.css';
// Apply Poppins font
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Optional: You can specify the font weights you want to use
});

export const metadata: Metadata = {
  title: "Mahadewabox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
